# .gitlab-ci.yml

spec:
  inputs:
    openmc_data_url:
      type: string
      description: URL for the OpenMC cross-section data tarball
      default: "https://openmc.org/assets/data/ENDF-B%2fVIII.0%2fcross_sections.xml" # Replace with the correct Box URL

stages:
  - lint
  - test
  - smoke
  - analyze

before_script:
  # Install dependencies
  - apt-get update && apt-get install -y python3-pip wget tar
  - pip3 install -r requirements.txt
  # Set PYTHONPATH for local modules
  - export PYTHONPATH=$(pwd)
  # Download and extract OpenMC data
  - wget ${openmc_data_url} -O cross_sections.xml.tar.gz
  - mkdir -p openmc_data
  - tar -xzf cross_sections.xml.tar.gz -C openmc_data
  # Set the environment variable for OpenMC
  - export OPENMC_CROSS_SECTIONS=$(pwd)/openmc_data/cross_sections.xml

lint:
  stage: lint
  image: python:3.12-slim
  script:
    # Add your linting commands here (e.g., flake8, black --check)
    - echo "Running linting..."
    # Example: flake8 .
    - echo "Linting finished."

test:
  stage: test
  image: python:3.12-slim
  script:
    - pytest recore/

smoke_run:
  stage: smoke
  image: python:3.12-slim
  script:
    - python3 recore/smoke_openmc.py

analyze_data:
  stage: analyze
  image: python:3.12-slim
  script:
    - python3 analyze.py
  artifacts:
    paths:
      - mesh_flux.csv
